# Port is required. Don't delete it!
port: 5000

# This is folder path. You can change it, but don't delete.
folder: "./testdir"

# Limit of the folder. Examples: 10 GB, 300 MB, 5.5 GB, 1 TB...
# You can remove it if you trust users.
storage_limit: "20 GB"

# This is secret encryption key to create encrypted tokens.
secret_encryption_key: "you must change it" # Example: 5asdasd1asd

# This is secret json web token key to create tokens.
secret_jwt_key: "you must change it" # Example: 5asdasd1asd

# Admin account properties
admin:
  username: "admin"
  email: "example@email.com"
  password: "123"
  permissions:
    read_directories: true
    read_files: true
    create: true
    change: true
    delete: true
    move: true
    download: true
    upload: true
    rename: true
    extract: true
    copy: true
    read_recovery: true
    use_recovery: true

# Holds deleted files. Accidentally, you might delete files that you don't want to delete.
recovery_bin: false

# Optionally you can limit recovery_bin storage. You can remove it if you want.
bin_storage_limit: "10 GB"

# Enable/Disable logging activities
log_activities: true

# Enable/Disable getting foldersize on start
get_foldersize_on_start: true